name: "cloud_storage"
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_DB=cloud_storage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=FK96KfaS4tyW
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 0olI6lz5CY66
    command: server --console-address ":9001" /data
      
volumes:
  pgdata:
  minio_storage: {}
